Remover itens do site / retirado texto embalagens ecologicas , retira…
the-strawhats/vrownie pull request #109
Opened 2022-08-09 00:48 UTC by AndySS-Maker

Description:

Oque foi feito no contexto dessa task foi,

- Retirado texto "embalagens ecológicas" 
- Retirado "ponto" no texto
- Retirado ícone do facebook, e centralizado novamente ícones no footer.

Screenshots:

Antes:

![image](https://user-images.githubusercontent.com/77177241/183538622-389730b2-b6ac-4711-862f-3c3516289894.png)

![image](https://user-images.githubusercontent.com/77177241/183538779-15ac0472-3e82-4f8b-bd15-3ae4bf4146fd.png)

Depois:

![image](https://user-images.githubusercontent.com/77177241/183538153-398f52dc-7943-40fa-9649-419f31d2ac5a.png)

![image](https://user-images.githubusercontent.com/77177241/183538218-690a92e9-cac9-422b-8a48-4a7e475d4964.png)

2022-08-09 22:43 UTC, fcidade commented
Tem que resolver alguns conflitos de merge tbm

2022-08-09 23:09 UTC, fcidade approved these changes

2022-08-09 23:11 UTC, amarilisselene commented
:earth_americas: :monkey: :monkey_face: :speak_no_evil:

2022-08-09 23:12 UTC, amarilisselene approved these changes

2022-08-09 23:14 UTC, fcidade commented
🧂 🔫 🚗 🪚 🧂 🧂 🧂 🧂 🧂 🕴️

2022-08-09 23:51 UTC, gabrielEscame requested changes

2022-08-09 23:51 UTC, gabrielEscame commented on src/view/Home/components/Footer/style.ts
> +
Mestre, oq acha de remover esse `nth-child` já que todos os elementos vão ter esse margin?

```suggestion
    margin: 0 8px;
 

```

2022-08-10 00:30 UTC, gabrielEscame requested changes

2022-08-10 00:30 UTC, gabrielEscame commented on src/view/Home/components/Footer/style.ts
>    }
Salve Sheriffe! 🤠 
Só faltou remover o `:nth-child(2)`.

2022-08-10 00:49 UTC, gabrielEscame approved these changes
🦇 👨🏻

2022-08-10 01:00 UTC, merged