Adicionar um botão para remover o produto do carrinho
the-strawhats/vrownie pull request #114
Opened 2022-08-10 01:06 UTC by fcidade

##### Description
- Limit decrease amount of items in the cart to 1
- Add delete button to each item on the cart

##### Screenshots
<img width="735" alt="image" src="https://user-images.githubusercontent.com/12754297/183788130-7bbcd5ae-3af4-4a97-afb9-fd69ac8d6874.png">

2022-08-10 01:09 UTC, amarilisselene commented
:imp: :dress: :sandal:

2022-08-10 01:11 UTC, amarilisselene approved these changes

2022-08-10 01:14 UTC, gabrielEscame requested changes

2022-08-10 01:14 UTC, gabrielEscame commented on src/utils/index.tsx
> +  const currentCartValue = previusData ? previusData : []
Aopaaa! 🤠 
Capitão, utilizando `||` ou o `??` não rolaria?

```suggestion
  const currentCartValue = previusData || []
```

2022-08-10 01:14 UTC, gabrielEscame commented on src/view/Cart/components/Order/style.ts
> +export const DeleteButton = styled.span`
Aooopa! 🤠 
Mestre, oq acha de usar um `styled.button`?

2022-08-10 01:15 UTC, gabrielEscame reviewed
Mestre, acha que poderíamos usar um ícone de lixeira ao invés de `excluir`? 🗑️

2022-08-15 22:11 UTC, fcidade commented on src/utils/index.tsx
> +  const currentCartValue = previusData ? previusData : []
lindo

2022-08-15 22:12 UTC, fcidade commented on src/view/Cart/components/Order/style.ts
> +export const DeleteButton = styled.span`
Vou testar como fica a estilização, queria algo vazio

2022-08-15 22:24 UTC, fcidade commented
> Order/style.ts

<img width="747" alt="image" src="https://user-images.githubusercontent.com/12754297/184729860-91b54919-6df8-431f-a609-6c9a07392af1.png">
Tá na mão capitão

2022-08-15 22:25 UTC, fcidade commented on src/view/Cart/components/Order/style.ts
> +export const DeleteButton = styled.span`
Arrumado!

2022-08-15 23:33 UTC, gabrielEscame requested changes

2022-08-15 23:33 UTC, gabrielEscame commented on src/view/Cart/components/Order/style.ts
> +  color: #a4351d;
Salve grande mestre Francis! 🎖️ 
O que você acha de alterar essa cor em hex pela nossa constante de cor?

```suggestion
  color: ${({theme}) => theme.colors.red.main };
```

2022-08-15 23:33 UTC, gabrielEscame commented on src/view/Cart/components/Order/style.ts
> +    color: #8cb175;
```suggestion
    color: ${({theme}) => theme.colors.green.main };
```

2022-08-16 00:51 UTC, gabrielEscame approved these changes
🐭 🦆 🐶

2022-08-16 01:36 UTC, merged